# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: add-telegraf-repo.yml
- include_tasks: install-telegraf.yml
- include_role:
    name: configure-telegraf-nodes
    tasks_from: generate-new-telegraf-configs
- include_tasks: create-telegraf-service.yml
- include_tasks: start-telegraf-service.yml
- include_tasks: enable-telegraf-service.yml
