# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- name: Start telegraf agents
  include_tasks: start-telegraf-service.yml
  with_items:
    - metrics
    - logs
  loop_control:
    loop_var: agent_type
