# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# Customize the specified `output_filter_entry` in the configuration file for
# the specified `measurement_set` based on the config parameters defined
# for that `measurement_set`/`input_filter_entry` pair
- set_fact:
    config_filename: "{{role_path}}/tasks/configure-{{output_filter_entry}}-output.yml"
# check the Ansible host to see if there is a YAML file to customize the named
# `output_filter_entry` in the configuration file for the named
# `measurement_set`
- local_action: stat path="{{config_filename}}"
  register: check_path
# if so, then include that file (to customize that `output_filter_entry`)
- include_tasks: "{{config_filename}}"
  when: check_path.stat.exists
