# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# Configure the agent section of the configuration file based on the input
# agent_config
- set_fact:
    precision: '{{(agent_config.config | default({})).precision | default("1ns")}}'
# Then create a new `/etc/telegraf/telegraf.conf` file containing only the
# agent configuration (the configuration for each of the "measurement sets"
# will be handled separately in configuration files created and placed into
# the `/etc/telegraf/telegraf.d` subdirectory)
- block:
  - name: Ensure the default telegraf agent configuration file is removed
    file:
      path: "/etc/telegraf/telegraf.conf"
      state: absent
  - name: Create a new (empty) configuration file from the template
    template:
      src: telegraf.conf.j2
      dest: /etc/telegraf/telegraf.conf
      mode: 0644
  become: true
